# Site settings
title: HA Leslie & Co | Independent Insurance Broker, Northern Ireland
shortTitle: HA Leslie & Co
email: info@haleslie.co.uk
phone: 07852 100 861
author:
description: Professional Insurance Broker, members of chartered Insurance Institute, all our advisors are CII Certificate qualified and above.
url:

# Build settings
permalink: :title/
sass:
  sass_dir: css
